{% set version = "2.2.0" %}
{% set processor = "cpu" if (cuda_compiler_version or "None") == "None" else "gpu" %}

# Prioritize gpu build if cudatoolkit can be installed (through __cuda virtual package)
{% set build = 6 %}
{% set build = build + 100 if processor == "gpu" else build %}

package:
  name: ceres-solver
  version: {{ version }}

source:
  url: http://ceres-solver.org/ceres-solver-{{ version }}.tar.gz
  sha256: 48b2302a7986ece172898477c3bcd6deb8fb5cf19b3327bc49969aad4cede82d

build:
  number: {{ build }}
  string: {{ processor }}h{{ PKG_HASH }}_{{ build }}
  skip: true  # [cuda_compiler_version == "11.8"]
  run_exports:
    - {{ pin_subpackage('ceres-solver', max_pin='x.x') }}
    - {{ pin_compatible('eigen', max_pin='x.x.x') }}
  ignore_run_exports_from:
    - libblas

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}         # [cuda_compiler_version != "None"]
    - make  # [unix]
  host:
    - glog
    # cmake find_package(LAPACK) needs blas
    # even though it's not linked
    - libblas
    - liblapack
    - metis
    - suitesparse
    - eigen
    - libcurand-dev                             # [(cuda_compiler_version or "None").startswith("12")]
    - cuda-cudart-dev                           # [(cuda_compiler_version or "None").startswith("12")]
    - cuda-version {{ cuda_compiler_version }}  # [(cuda_compiler_version or "None").startswith("12")]
  run:
    - {{ pin_compatible('eigen', max_pin='x.x.x') }}
    - __cuda >={{ cuda_compiler_version }}  # [cuda_compiler_version != "None"]

test:
  requires:
    - cmake
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - make  # [unix]
  files:
    - tests/
  source_files:
    - examples/helloworld.cc
  commands:
    - test -f ${PREFIX}/include/ceres/ceres.h  # [unix]
    - test -f ${PREFIX}/lib/libceres${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\include\\ceres\\ceres.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\ceres.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\ceres.dll exit 1  # [win]

about:
  home: http://ceres-solver.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A large scale non-linear optimization library

extra:
  recipe-maintainers:
    - jschueller
    - seanyen
    - hobu
