{% set version = "2.2.0" %}

package:
  name: ceres-solver
  version: {{ version }}

source:
  url: http://ceres-solver.org/ceres-solver-{{ version }}.tar.gz
  sha256: 48b2302a7986ece172898477c3bcd6deb8fb5cf19b3327bc49969aad4cede82d

build:
  number: 3
  run_exports:
    - {{ pin_subpackage('ceres-solver', max_pin='x.x') }}
    - {{ pin_compatible('eigen', max_pin='x.x.x') }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make
  host:
    - glog
    - gflags
    - libblas
    - libcblas
    - liblapack
    - suitesparse
    - tbb
    - eigen

  run:
    - glog
    - gflags
    - suitesparse
    - tbb
    - eigen

test:
  commands:
    - test -f ${PREFIX}/include/ceres/ceres.h  # [unix]
    - test -f ${PREFIX}/lib/libceres${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\include\\ceres\\ceres.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\ceres.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\ceres.dll exit 1  # [win]

about:
  home: http://ceres-solver.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A large scale non-linear optimization library

extra:
  recipe-maintainers:
    - jschueller
    - seanyen
    - hobu
